# Site settings
title: Vivien's Blog
email: vivien.leonard@gmail.com
description: Another software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vivienleonard.github.io" # the base hostname & protocol for your site
twitter_username: vivienleonard
github_username:  vivienleonard

# Build settings
markdown: kramdown
paginate: 2
paginate_path: "blog/page:num/"
